<template><div><h1 id="tsconfig-模板" tabindex="-1"><a class="header-anchor" href="#tsconfig-模板"><span>tsconfig 模板</span></a></h1>
<div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json" data-title="json"><pre v-pre><code><span class="line"><span class="token punctuation">{</span></span>
<span class="line">  <span class="token property">"extends"</span><span class="token operator">:</span> <span class="token string">"../tsconfig.json"</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"compilerOptions"</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">/* Visit https://aka.ms/tsconfig.json to read more about this file */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Basic Options */</span></span>
<span class="line">    <span class="token comment">// "incremental": true,                         /* Enable incremental compilation */</span></span>
<span class="line">    <span class="token property">"target"</span><span class="token operator">:</span> <span class="token string">"es6"</span><span class="token punctuation">,</span>                             <span class="token comment">/* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', 'ES2021', or 'ESNEXT'. */</span></span>
<span class="line">    <span class="token property">"module"</span><span class="token operator">:</span> <span class="token string">"ES6"</span><span class="token punctuation">,</span>                             <span class="token comment">/* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */</span></span>
<span class="line">    <span class="token property">"lib"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"es6"</span><span class="token punctuation">,</span> <span class="token string">"dom"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>                       <span class="token comment">/* Specify library files to be included in the compilation. */</span></span>
<span class="line">    <span class="token property">"allowJs"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>                            <span class="token comment">/* Allow javascript files to be compiled. */</span></span>
<span class="line">    <span class="token comment">// "checkJs": true,                             /* Report errors in .js files. */</span></span>
<span class="line">    <span class="token property">"jsx"</span><span class="token operator">:</span> <span class="token string">"preserve"</span><span class="token punctuation">,</span>                           <span class="token comment">/* Specify JSX code generation: 'preserve', 'react-native', 'react', 'react-jsx' or 'react-jsxdev'. */</span></span>
<span class="line">    <span class="token comment">// "declaration": true,                        /* Generates corresponding '.d.ts' file. */</span></span>
<span class="line">    <span class="token comment">// "declarationMap": true,                      /* Generates a sourcemap for each corresponding '.d.ts' file. */</span></span>
<span class="line">    <span class="token property">"sourceMap"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>                          <span class="token comment">/* Generates corresponding '.map' file. */</span></span>
<span class="line">    <span class="token comment">// "outFile": "./",                             /* Concatenate and emit output to single file. */</span></span>
<span class="line">    <span class="token comment">// "outDir": "./dist",                          /* Redirect output structure to the directory. */</span></span>
<span class="line">    <span class="token comment">// "rootDir": "./src",                          /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */</span></span>
<span class="line">    <span class="token comment">// "composite": true,                           /* Enable project compilation */</span></span>
<span class="line">    <span class="token comment">// "tsBuildInfoFile": "./",                     /* Specify file to store incremental compilation information */</span></span>
<span class="line">    <span class="token property">"removeComments"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>                     <span class="token comment">/* Do not emit comments to output. */</span></span>
<span class="line">    <span class="token property">"noEmit"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                              <span class="token comment">/* Do not emit outputs. */</span></span>
<span class="line">    <span class="token comment">// "importHelpers": true,                       /* Import emit helpers from 'tslib'. */</span></span>
<span class="line">    <span class="token comment">// "downlevelIteration": true,                  /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */</span></span>
<span class="line">    <span class="token comment">// "isolatedModules": true,                     /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Strict Type-Checking Options */</span></span>
<span class="line">    <span class="token comment">// "strict": true,                              /* Enable all strict type-checking options. */</span></span>
<span class="line">    <span class="token comment">// "noImplicitAny": true,                       /* Raise error on expressions and declarations with an implied 'any' type. */</span></span>
<span class="line">    <span class="token comment">// "strictNullChecks": true,                    /* Enable strict null checks. */</span></span>
<span class="line">    <span class="token property">"strictFunctionTypes"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                 <span class="token comment">/* Enable strict checking of function types. */</span></span>
<span class="line">    <span class="token comment">// "strictBindCallApply": true,                 /* Enable strict 'bind', 'call', and 'apply' methods on functions. */</span></span>
<span class="line">    <span class="token comment">// "strictPropertyInitialization": true,        /* Enable strict checking of property initialization in classes. */</span></span>
<span class="line">    <span class="token comment">// "noImplicitThis": true,                      /* Raise error on 'this' expressions with an implied 'any' type. */</span></span>
<span class="line">    <span class="token property">"alwaysStrict"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                        <span class="token comment">/* Parse in strict mode and emit "use strict" for each source file. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Additional Checks */</span></span>
<span class="line">    <span class="token property">"noUnusedLocals"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                      <span class="token comment">/* Report errors on unused locals. */</span></span>
<span class="line">    <span class="token property">"noUnusedParameters"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                  <span class="token comment">/* Report errors on unused parameters. */</span></span>
<span class="line">    <span class="token property">"noImplicitReturns"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                   <span class="token comment">/* Report error when not all code paths in function return a value. */</span></span>
<span class="line">    <span class="token comment">// "noFallthroughCasesInSwitch": true,          /* Report errors for fallthrough cases in switch statement. */</span></span>
<span class="line">    <span class="token comment">// "noUncheckedIndexedAccess": true,            /* Include 'undefined' in index signature results */</span></span>
<span class="line">    <span class="token comment">// "noImplicitOverride": true,                  /* Ensure overriding members in derived classes are marked with an 'override' modifier. */</span></span>
<span class="line">    <span class="token comment">// "noPropertyAccessFromIndexSignature": true,  /* Require undeclared properties from index signatures to use element accesses. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Module Resolution Options */</span></span>
<span class="line">    <span class="token property">"moduleResolution"</span><span class="token operator">:</span> <span class="token string">"node"</span><span class="token punctuation">,</span>                  <span class="token comment">/* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */</span></span>
<span class="line">    <span class="token property">"baseUrl"</span><span class="token operator">:</span> <span class="token string">"."</span><span class="token punctuation">,</span>                              <span class="token comment">/* Base directory to resolve non-absolute module names. */</span></span>
<span class="line">    <span class="token property">"paths"</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span>                                 <span class="token comment">/* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */</span></span>
<span class="line">    <span class="token comment">// "rootDirs": [],                              /* List of root folders whose combined content represents the structure of the project at runtime. */</span></span>
<span class="line">    <span class="token comment">// "typeRoots": [],                             /* List of folders to include type definitions from. */</span></span>
<span class="line">    <span class="token property">"types"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>                                 <span class="token comment">/* Type declaration files to be included in compilation. */</span></span>
<span class="line">    <span class="token property">"allowSyntheticDefaultImports"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>        <span class="token comment">/* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */</span></span>
<span class="line">    <span class="token property">"esModuleInterop"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>                     <span class="token comment">/* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */</span></span>
<span class="line">    <span class="token comment">// "preserveSymlinks": true,                    /* Do not resolve the real path of symlinks. */</span></span>
<span class="line">    <span class="token comment">// "allowUmdGlobalAccess": true,                /* Allow accessing UMD globals from modules. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Source Map Options */</span></span>
<span class="line">    <span class="token comment">// "sourceRoot": "",                            /* Specify the location where debugger should locate TypeScript files instead of source locations. */</span></span>
<span class="line">    <span class="token comment">// "mapRoot": "",                               /* Specify the location where debugger should locate map files instead of generated locations. */</span></span>
<span class="line">    <span class="token comment">// "inlineSourceMap": true,                     /* Emit a single file with source maps instead of having a separate file. */</span></span>
<span class="line">    <span class="token comment">// "inlineSources": true,                       /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Experimental Options */</span></span>
<span class="line">    <span class="token property">"experimentalDecorators"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>              <span class="token comment">/* Enables experimental support for ES7 decorators. */</span></span>
<span class="line">    <span class="token comment">// "emitDecoratorMetadata": true,               /* Enables experimental support for emitting type metadata for decorators. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">/* Advanced Options */</span></span>
<span class="line">    <span class="token comment">// "skipLibCheck": true,                           /* Skip type checking of declaration files. */</span></span>
<span class="line">    <span class="token comment">// "forceConsistentCasingInFileNames": true        /* Disallow inconsistently-cased references to the same file. */</span></span>
<span class="line"></span>
<span class="line">    <span class="token property">"preserveConstEnums"</span><span class="token operator">:</span> <span class="token boolean">true</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"exclude"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"include"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token property">"files"</span><span class="token operator">:</span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string">"**/**/*.ts"</span></span>
<span class="line">  <span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


