<template><div><h1 id="ab-manager-codec-加密解密" tabindex="-1"><a class="header-anchor" href="#ab-manager-codec-加密解密"><span>ab-manager-codec 加密解密</span></a></h1>
<h2 id="_1-摘要加密" tabindex="-1"><a class="header-anchor" href="#_1-摘要加密"><span>1. 摘要加密</span></a></h2>
<h3 id="_1-1-md5" tabindex="-1"><a class="header-anchor" href="#_1-1-md5"><span>1.1 MD5</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">MD5</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'9944781'</span><span class="token punctuation">,</span></span>
<span class="line">    hashData<span class="token operator">=</span> <span class="token constant">MD5</span><span class="token punctuation">.</span><span class="token function">hash</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-2-sha1" tabindex="-1"><a class="header-anchor" href="#_1-2-sha1"><span>1.2 SHA1</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">SHA1</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'9944781'</span><span class="token punctuation">,</span></span>
<span class="line">    hashData<span class="token operator">=</span> <span class="token constant">SHA1</span><span class="token punctuation">.</span><span class="token function">hash</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-3-sm3" tabindex="-1"><a class="header-anchor" href="#_1-3-sm3"><span>1.3 SM3</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">SM3</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'9944781'</span><span class="token punctuation">,</span></span>
<span class="line">    hashData<span class="token operator">=</span> <span class="token constant">SM3</span><span class="token punctuation">.</span><span class="token function">hash</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-加密解密" tabindex="-1"><a class="header-anchor" href="#_2-加密解密"><span>2. 加密解密</span></a></h2>
<h3 id="_2-1-sm2" tabindex="-1"><a class="header-anchor" href="#_2-1-sm2"><span>2.1 SM2</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">SM2</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'我是机密信息'</span><span class="token punctuation">,</span></span>
<span class="line">    keypair <span class="token operator">=</span> <span class="token constant">SM2</span><span class="token punctuation">.</span><span class="token function">generateKeyPairHex</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    publicKey <span class="token operator">=</span> keypair<span class="token punctuation">.</span>publicKey<span class="token punctuation">,</span></span>
<span class="line">    privateKey <span class="token operator">=</span> keypair<span class="token punctuation">.</span>privateKey<span class="token punctuation">,</span></span>
<span class="line">    encryptData <span class="token operator">=</span> <span class="token constant">SM2</span><span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> publicKey<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    decryptData <span class="token operator">=</span> <span class="token constant">SM2</span><span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>encryptData<span class="token punctuation">,</span> privateKey<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-2-sm4" tabindex="-1"><a class="header-anchor" href="#_2-2-sm4"><span>2.2 SM4</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">SM4</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'我是机密信息'</span><span class="token punctuation">,</span></span>
<span class="line">    secretKey <span class="token operator">=</span> <span class="token string">'0123456789abcdeffedcba9876543210'</span><span class="token punctuation">,</span></span>
<span class="line">    encryptData <span class="token operator">=</span> <span class="token constant">SM4</span><span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    decryptData <span class="token operator">=</span> <span class="token constant">SM4</span><span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>encryptData<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-3-des" tabindex="-1"><a class="header-anchor" href="#_2-3-des"><span>2.3 DES</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> <span class="token constant">DES</span> <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'我是机密信息'</span><span class="token punctuation">,</span></span>
<span class="line">    secretKey <span class="token operator">=</span> <span class="token string">'0123456789abcdeffedcba9876543210'</span><span class="token punctuation">,</span></span>
<span class="line">    encryptData <span class="token operator">=</span> <span class="token constant">DES</span><span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    decryptData <span class="token operator">=</span> <span class="token constant">DES</span><span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>encryptData<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-4-tripledes" tabindex="-1"><a class="header-anchor" href="#_2-4-tripledes"><span>2.4 TripleDES</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> TripleDES <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'我是机密信息'</span><span class="token punctuation">,</span></span>
<span class="line">    secretKey <span class="token operator">=</span> <span class="token string">'0123456789abcdeffedcba9876543210'</span><span class="token punctuation">,</span></span>
<span class="line">    encryptData <span class="token operator">=</span> TripleDES<span class="token punctuation">.</span><span class="token function">encrypt</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    decryptData <span class="token operator">=</span> TripleDES<span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>encryptData<span class="token punctuation">,</span> secretKey<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_3-编码解码" tabindex="-1"><a class="header-anchor" href="#_3-编码解码"><span>3. 编码解码</span></a></h2>
<h3 id="_3-1-base64" tabindex="-1"><a class="header-anchor" href="#_3-1-base64"><span>3.1 Base64</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Base64 <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@agree/ab-manager-codec'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> message <span class="token operator">=</span> <span class="token string">'我是一条消息'</span><span class="token punctuation">,</span></span>
<span class="line">    encodeData <span class="token operator">=</span> Base64<span class="token punctuation">.</span><span class="token function">encode</span><span class="token punctuation">(</span>message<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    decodeData <span class="token operator">=</span> Base64<span class="token punctuation">.</span><span class="token function">decode</span><span class="token punctuation">(</span>encodeData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


