<template><div><h1 id="ab-plugin-peer-通讯组件" tabindex="-1"><a class="header-anchor" href="#ab-plugin-peer-通讯组件"><span>ab-plugin-peer@通讯组件</span></a></h1>
<h2 id="_1-引入" tabindex="-1"><a class="header-anchor" href="#_1-引入"><span>1. 引入</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> WSPeer <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@agree/ab-plugin-peer"</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="_2-事件方法的使用" tabindex="-1"><a class="header-anchor" href="#_2-事件方法的使用"><span>2. 事件方法的使用</span></a></h2>
<h3 id="_2-1-初始化peer通讯单元。" tabindex="-1"><a class="header-anchor" href="#_2-1-初始化peer通讯单元。"><span>2.1 初始化peer通讯单元。</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> context <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"ab5web"</span><span class="token punctuation">,</span></span>
<span class="line">                <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"ws://127.0.0.1:"</span> <span class="token operator">+</span> Hub<span class="token punctuation">.</span>port<span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">let</span> peer <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">WSPeer</span><span class="token punctuation">(</span>context<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-2-发送同步消息-有返回值" tabindex="-1"><a class="header-anchor" href="#_2-2-发送同步消息-有返回值"><span>2.2 发送同步消息（有返回值）</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> exchangeReq <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">to</span><span class="token operator">:</span> <span class="token string">"ab3"</span><span class="token punctuation">,</span><span class="token comment">//发送给谁</span></span>
<span class="line">            <span class="token literal-property property">command</span><span class="token operator">:</span> <span class="token string">"openTrade"</span><span class="token punctuation">,</span><span class="token comment">//路由名称</span></span>
<span class="line">            <span class="token literal-property property">body</span><span class="token operator">:</span> body<span class="token comment">//通讯报文(json)</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">peer<span class="token punctuation">.</span><span class="token function">exchangeAsync</span><span class="token punctuation">(</span>exchangeReq<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-3-发送异步消息" tabindex="-1"><a class="header-anchor" href="#_2-3-发送异步消息"><span>2.3 发送异步消息</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> exchangeReq <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token literal-property property">to</span><span class="token operator">:</span> <span class="token string">"ab3"</span><span class="token punctuation">,</span><span class="token comment">//发送给谁</span></span>
<span class="line">            <span class="token literal-property property">command</span><span class="token operator">:</span> <span class="token string">"openTrade"</span><span class="token punctuation">,</span><span class="token comment">//路由名称</span></span>
<span class="line">            <span class="token literal-property property">body</span><span class="token operator">:</span> body<span class="token comment">//通讯报文(json)</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">peer<span class="token punctuation">.</span><span class="token function">sendAsync</span><span class="token punctuation">(</span>exchangeReq<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-4-注册路由" tabindex="-1"><a class="header-anchor" href="#_2-4-注册路由"><span>2.4 注册路由</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">this</span><span class="token punctuation">.</span>peer<span class="token punctuation">.</span><span class="token function">registerCommand</span><span class="token punctuation">(</span><span class="token string">"路由名称"</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">args</span><span class="token operator">:</span> any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token keyword">null</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


