<template><div><h1 id="ab-plugin-trade-ab5内嵌ab3交易专属" tabindex="-1"><a class="header-anchor" href="#ab-plugin-trade-ab5内嵌ab3交易专属"><span>ab-plugin-trade@ab5内嵌ab3交易专属</span></a></h1>
<h2 id="_1-引入" tabindex="-1"><a class="header-anchor" href="#_1-引入"><span>1. 引入</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> AB3Trade <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@agree/ab-plugin-trade"</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="_2-事件方法的使用" tabindex="-1"><a class="header-anchor" href="#_2-事件方法的使用"><span>2. 事件方法的使用</span></a></h2>
<h3 id="_2-1-打开并内嵌ab3交易" tabindex="-1"><a class="header-anchor" href="#_2-1-打开并内嵌ab3交易"><span>2.1 打开并内嵌ab3交易</span></a></h3>
<blockquote>
<p>(body为ab3专属交易报文;x,y为内嵌坐标;width、height为打开交易大小;parentTitle为内嵌父窗体)。</p>
</blockquote>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">openTrade</span><span class="token punctuation">(</span>body<span class="token operator">:</span> any<span class="token punctuation">,</span> <span class="token literal-property property">x</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">y</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">width</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> number<span class="token punctuation">,</span> parentTitle<span class="token operator">?</span><span class="token operator">:</span> String<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-2-同步ab5柜员信息到ab3" tabindex="-1"><a class="header-anchor" href="#_2-2-同步ab5柜员信息到ab3"><span>2.2 同步ab5柜员信息到ab3</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">tellerInfo</span><span class="token punctuation">(</span>body<span class="token operator">:</span> any<span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-3-内嵌窗体" tabindex="-1"><a class="header-anchor" href="#_2-3-内嵌窗体"><span>2.3 内嵌窗体</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span> <span class="token function">embedTrade</span><span class="token punctuation">(</span>body<span class="token operator">:</span> any<span class="token punctuation">,</span> <span class="token literal-property property">x</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">y</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">width</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> number<span class="token punctuation">,</span> parentTitle<span class="token operator">?</span><span class="token operator">:</span> String<span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-4-关闭ab3交易" tabindex="-1"><a class="header-anchor" href="#_2-4-关闭ab3交易"><span>2.4 关闭ab3交易</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span> <span class="token function">closeTrade</span><span class="token punctuation">(</span>body<span class="token operator">:</span> any<span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-5-截图并返回base64字符串" tabindex="-1"><a class="header-anchor" href="#_2-5-截图并返回base64字符串"><span>2.5 截图并返回base64字符串</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span> <span class="token function">screenShoot</span><span class="token punctuation">(</span>x<span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">y</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">width</span><span class="token operator">:</span> number<span class="token punctuation">,</span> <span class="token literal-property property">height</span><span class="token operator">:</span> number<span class="token punctuation">)</span><span class="token operator">:</span> String<span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-6-隐藏或显示ab3交易" tabindex="-1"><a class="header-anchor" href="#_2-6-隐藏或显示ab3交易"><span>2.6 隐藏或显示ab3交易</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">hideOrShowTrade</span><span class="token punctuation">(</span>body<span class="token operator">:</span> any<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-7-linux版本锁屏" tabindex="-1"><a class="header-anchor" href="#_2-7-linux版本锁屏"><span>2.7 linux版本锁屏</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">startLockScreen</span><span class="token punctuation">(</span>time<span class="token operator">:</span> number<span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="_2-8-结束锁屏" tabindex="-1"><a class="header-anchor" href="#_2-8-结束锁屏"><span>2.8 结束锁屏</span></a></h3>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">   AB3Trade<span class="token punctuation">.</span><span class="token function">getInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">stopLockScreen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


