<template><div><h2 id="eventemitter到底是个啥" tabindex="-1"><a class="header-anchor" href="#eventemitter到底是个啥"><span>EventEmitter到底是个啥？</span></a></h2>
<p>EventEmitter实际上是一种遵循<strong>发布订阅</strong>设计模式的事件触发器。其思想为：用户去监听某个事件，当该事件发生时，则监听该事件的函数会被调用。
现在无论在前端还是后端，对于事件触发器的设计思路有很多，比如Node.js中就有一个<a href="http://nodejs.cn/api/events.html#events_class_eventemitter" target="_blank" rel="noopener noreferrer">EventEmitter</a>，当所有的异步 I/O 操作在完成时都会发送一个事件到事件队列。Node.js 里面的许多对象都会分发事件：一个<code v-pre>net.Server</code>对象会在每次有新连接时触发一个事件， 一个<code v-pre>fs.readStream</code> 对象会在文件被打开的时候触发一个事件。 所有这些产生事件的对象都是 <code v-pre>events.EventEmitter</code> 的实例。你可以通过创建一个<code v-pre>eventEmitter </code>对象，去对这些事件进行监听，例如：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line"><span class="token comment">//event.js文件</span></span>
<span class="line"><span class="token keyword">var</span> EventEmitter <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'events'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>EventEmitter<span class="token punctuation">;</span> </span>
<span class="line"><span class="token keyword">var</span> event <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line">event<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'some_event'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> </span>
<span class="line">	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'some_event 事件触发'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"><span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> </span>
<span class="line">	event<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token string">'some_event'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">;</span> </span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上面逻辑的执行结果为：运行这段代码，1 秒后控制台输出了 <strong>'some_event 事件触发'</strong>。其原理是 event 对象注册了事件 some_event 的一个监听器，然后我们通过 setTimeout 在 1000 毫秒以后向 event 对象发送事件 some_event，此时会调用some_event 的监听器。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">$ node event<span class="token punctuation">.</span>js </span>
<span class="line">some_event 事件触发</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="如何设计一款事件触发器" tabindex="-1"><a class="header-anchor" href="#如何设计一款事件触发器"><span>如何设计一款事件触发器？</span></a></h2>
<p>让我们分析一下一个事件触发器应该具备哪些功能：</p>
<ul>
<li>提供整个事件触发器的构造函数和触发器的dispose函数</li>
<li>提供建立事件监听的函数</li>
<li>提供卸载事件监听的函数</li>
<li>提供触发某个事件的函数</li>
<li>当某个事件发生时，所有监听该事件的函数均需要被执行
那么，首先我们要思考一下，有哪种数据类型可以满足上述要求？这里提出一个数据类型：<code v-pre>ES6</code>种的<code v-pre>Iterable</code>接口
ES中能够表示有结构的数据类型越来越多，以前有数组、对象等等，ES2015中新增了Map和Set对象。为了给各种各样的数据结构提供统一遍历方式，<strong>ES2015提供了Iterable（可迭代的）接口</strong>，如果想要对某个对象进行<strong>for…of</strong>遍历，则需要对该对象实现Iterable接口。那么，让我们首先来分析以下一个数组对象的原型，是如何对Iterable接口进行实现的：
<img src="@source/AB产品知识库20240403/images/知识探索/前端/Eclipse-Thiea/C端新技术调研篇2——如何设计一个合理的EventEmitter——事件发布订阅管理器？/1.png" alt="arr原型.png">
通过观察我们大概可以猜到，<code v-pre>Iterable</code>接口约定的就是对象当中必须要去挂载一个叫做<code v-pre>iterator</code>的方法。<code v-pre>iterator</code>方法是干什么的呢?我们定义一个数组，手动调用一下它的<code v-pre>iterator</code>方法，它返回的是数组的迭代器对象，展开发现，对象里面有一个<code v-pre>next</code>方法：
<img src="@source/AB产品知识库20240403/images/知识探索/前端/Eclipse-Thiea/C端新技术调研篇2——如何设计一个合理的EventEmitter——事件发布订阅管理器？/2.png" alt="arr种iterator实现.png">
我们先定义一个变量来接收返回的迭代器对象，然后手动调用一下它的next方法
<img src="@source/AB产品知识库20240403/images/知识探索/前端/Eclipse-Thiea/C端新技术调研篇2——如何设计一个合理的EventEmitter——事件发布订阅管理器？/3.png" alt="iterable实现.png">
从上可以发现，在这个迭代器当中，内部维护了一个数据指针，每调用一次<code v-pre>next()</code>，这个指针都会往后移一位。<code v-pre>done</code>属性的作用是标识里面的数据是否被遍历完了。而使用<strong>for...of</strong>方法进行遍历时，其内部就是去调用被遍历对象的<code v-pre>iterable</code>方法得到一个迭代器，从而去遍历内部所有的数据。因此，我们可以考虑实现Iterable接口来搞一些事情，比如用于遍历所有事件触发器的监听函数。</li>
</ul>
<h2 id="具体该怎么做" tabindex="-1"><a class="header-anchor" href="#具体该怎么做"><span>具体该怎么做？</span></a></h2>
<blockquote>
<p>Step 1：设计一个CallbackList对象</p>
</blockquote>
<p>首先，需要设计一个CallbackList对象，其意义在于每当新定义一个事件时，会管理所有对于该事件的监听函数，其实现了Iterable接口，其主要功能为：</p>
<ul>
<li>声明构造器和销毁该对象的方法。</li>
<li>维护所有的<code v-pre>listener</code>，包括对<code v-pre>listener</code>的<code v-pre>add</code>、<code v-pre>remove</code>。</li>
<li>重写<code v-pre>Symbol.iterator</code>构造函数，从而让<strong>for...of</strong>去调用该对象迭代器时，用于触发所存储的对应<code v-pre>listener</code>监听。</li>
<li>提供一个方法用于判断某个事件的<code v-pre>listener</code>的数量。</li>
<li>提供一个方法用于判断某个事件的<code v-pre>listener</code>是否存在。
由于最近在研究Theia，其EventEmitter设计比较完善，让我们看看Theia中EventEmitter里面对于这种监听管理对象的代码，首先来分析下其重写Symbol.iterator的方法和增加一个监听事件以及调用所有监听事件的方法：</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">type</span> <span class="token class-name">Callback</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">CallbackList</span> <span class="token keyword">implements</span> <span class="token class-name">Iterable<span class="token operator">&lt;</span>Callback<span class="token operator">></span></span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">private</span> _callbacks<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">|</span> <span class="token keyword">undefined</span><span class="token punctuation">;</span></span>
<span class="line">  	<span class="token keyword">private</span> _contexts<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">|</span> <span class="token keyword">undefined</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token comment">// tslint:disable-next-line:typedef</span></span>
<span class="line">    <span class="token keyword">public</span> <span class="token punctuation">[</span>Symbol<span class="token punctuation">.</span>iterator<span class="token punctuation">]</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">[</span>Symbol<span class="token punctuation">.</span>iterator<span class="token punctuation">]</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">const</span> callbacks <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">const</span> contexts <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_contexts<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">return</span> callbacks<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span>callback<span class="token punctuation">,</span> i<span class="token punctuation">)</span> <span class="token operator">=></span></span>
<span class="line">            <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">callback</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span>contexts<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">,</span> args<span class="token punctuation">)</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">[</span>Symbol<span class="token punctuation">.</span>iterator<span class="token punctuation">]</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">public</span> <span class="token function">add</span><span class="token punctuation">(</span>callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> context<span class="token operator">:</span> <span class="token builtin">any</span> <span class="token operator">=</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> bucket<span class="token operator">?</span><span class="token operator">:</span> Disposable<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">this</span><span class="token punctuation">.</span>_contexts <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>callback<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">this</span><span class="token punctuation">.</span>_contexts<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>context<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token builtin">Array</span><span class="token punctuation">.</span><span class="token function">isArray</span><span class="token punctuation">(</span>bucket<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            bucket<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token function-variable function">dispose</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>callback<span class="token punctuation">,</span> context<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">	<span class="token keyword">public</span> <span class="token function">invoke</span><span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> ret<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> callback <span class="token keyword">of</span> <span class="token keyword">this</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">try</span> <span class="token punctuation">{</span></span>
<span class="line">                ret<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token function">callback</span><span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">return</span> ret<span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先，<code v-pre>add</code>方法里面对<code v-pre>callbacks</code>和<code v-pre>contexts</code>进行了初始化。前者存储了所有对于该事件的监听函数，后者存储着每一个监听函数对应的作用域，后面我们来介绍为什么要把作用域也进行存储。当我们触发一个事件时，则会调用<code v-pre>invoke</code>函数，<code v-pre>invoke</code>函数内通过<strong>for...of</strong>去调用该CallbackList对象迭代器时，会直接触发我们重写的<code v-pre>Symbol.iterator</code>方法。<code v-pre>Symbol.iterator</code>方法中，会通过<code v-pre>apply</code>方法触发所有监听函数，并将<code v-pre>context</code>作用域也传递至监听函数内。</p>
<blockquote>
<p>Step 2：设计Emitter</p>
</blockquote>
<p>Emitter作为事件触发器，可以对外提供API用于建立监听和触发事件。同时，也可以管理每一个事件地监听数量，以保证不会因为Listener过多造成内存溢出。在Theia地EventEmitter中，其首先声明了一个<code v-pre>event</code>的<code v-pre>get</code>方法，用于让外部类订阅一个事件：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">Emitter<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token operator">=</span> <span class="token builtin">any</span><span class="token operator">></span></span><span class="token punctuation">{</span></span>
<span class="line"><span class="token operator">...</span><span class="token operator">...</span></span>
<span class="line"><span class="token doc-comment comment">/**</span>
<span class="line">    * For the public to allow to subscribe</span>
<span class="line">    * to events from this Emitter</span>
<span class="line">    */</span></span>
<span class="line">    <span class="token keyword">get</span> <span class="token function">event</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> Event<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>_event<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">this</span><span class="token punctuation">.</span>_event <span class="token operator">=</span> Object<span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token function-variable function">listener</span><span class="token operator">:</span> <span class="token punctuation">(</span>e<span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">,</span> thisArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> disposables<span class="token operator">?</span><span class="token operator">:</span> Disposable<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">CallbackList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>_options <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_options<span class="token punctuation">.</span>onFirstListenerAdd <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token keyword">this</span><span class="token punctuation">.</span>_options<span class="token punctuation">.</span><span class="token function">onFirstListenerAdd</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">                <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>listener<span class="token punctuation">,</span> thisArgs<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token keyword">const</span> removeMaxListenersCheck <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">checkMaxListeners</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>_event<span class="token punctuation">.</span>maxListeners<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">                <span class="token keyword">const</span> result<span class="token operator">:</span> Disposable <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token function-variable function">dispose</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">                        <span class="token keyword">if</span> <span class="token punctuation">(</span>removeMaxListenersCheck<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                            <span class="token function">removeMaxListenersCheck</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                        <span class="token punctuation">}</span></span>
<span class="line">                        result<span class="token punctuation">.</span>dispose <span class="token operator">=</span> Emitter<span class="token punctuation">.</span>_noop<span class="token punctuation">;</span></span>
<span class="line">                        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>_disposed<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                            <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>listener<span class="token punctuation">,</span> thisArgs<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                            result<span class="token punctuation">.</span>dispose <span class="token operator">=</span> Emitter<span class="token punctuation">.</span>_noop<span class="token punctuation">;</span></span>
<span class="line">                            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>_options <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_options<span class="token punctuation">.</span>onLastListenerRemove <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                                <span class="token keyword">this</span><span class="token punctuation">.</span>_options<span class="token punctuation">.</span><span class="token function">onLastListenerRemove</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                            <span class="token punctuation">}</span></span>
<span class="line">                        <span class="token punctuation">}</span></span>
<span class="line">                    <span class="token punctuation">}</span></span>
<span class="line">                <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token builtin">Array</span><span class="token punctuation">.</span><span class="token function">isArray</span><span class="token punctuation">(</span>disposables<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    disposables<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">                <span class="token keyword">return</span> result<span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">                maxListeners<span class="token operator">:</span> Emitter<span class="token punctuation">.</span><span class="token constant">LEAK_WARNING_THRESHHOLD</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">            <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_event<span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token operator">...</span><span class="token operator">...</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先，<code v-pre>event</code>方法中会判断某个事件是否声明了<code v-pre>CallbackList</code>实例，如果没有的话，则会创建一个，并将外部传递的监听函数通过调用<code v-pre>CallbackList</code>的<code v-pre>add</code>方法添加进来，同时也将作用域上下文传递了进来。每当触发一个事件时，Emitter也提供了一个<code v-pre>fire</code>方法：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">Emitter<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token operator">=</span> <span class="token builtin">any</span><span class="token operator">></span></span><span class="token punctuation">{</span></span>
<span class="line"><span class="token operator">...</span><span class="token operator">...</span></span>
<span class="line"><span class="token doc-comment comment">/**</span>
<span class="line">     * To be kept private to fire an event to</span>
<span class="line">     * subscribers</span>
<span class="line">     */</span></span>
<span class="line">    <span class="token function">fire</span><span class="token punctuation">(</span>event<span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">this</span><span class="token punctuation">.</span>_callbacks<span class="token punctuation">.</span><span class="token function">invoke</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token operator">...</span><span class="token operator">...</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其会调用<code v-pre>event</code>方法中声明的<code v-pre>Callbacklist</code>对象里的<code v-pre>invoke</code>方法，实现对于该对象迭代器的触发，从而将事件通知给所有的监听函数。让我们写一个测试案例试一下：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">const</span> emitter <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Emitter<span class="token operator">&lt;</span><span class="token builtin">string</span><span class="token operator">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">let</span> listener <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">    onmessage<span class="token operator">:</span> emitter<span class="token punctuation">.</span>event</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">listener<span class="token punctuation">.</span><span class="token function">onmessage</span><span class="token punctuation">(</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span><span class="token keyword">this</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line">emitter<span class="token punctuation">.</span><span class="token function">fire</span><span class="token punctuation">(</span><span class="token string">"666"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">emitter<span class="token punctuation">.</span><span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们new了一个Emitter实例，并且绑定了一个监听函数，内部输出一下作用域this和触发事件的msg，控制台运行效果如下：</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js" data-title="js"><pre v-pre><code><span class="line">$ ts<span class="token operator">-</span>node test<span class="token punctuation">.</span>ts</span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">  <span class="token literal-property property">Event</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token literal-property property">None</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token function">Function</span> <span class="token punctuation">(</span>anonymous<span class="token punctuation">)</span><span class="token punctuation">]</span> <span class="token punctuation">{</span> <span class="token literal-property property">maxListeners</span><span class="token operator">:</span> <span class="token number">0</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">map</span><span class="token operator">:</span> <span class="token punctuation">[</span>Function<span class="token operator">:</span> map<span class="token punctuation">]</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token literal-property property">Emitter</span><span class="token operator">:</span> <span class="token punctuation">[</span>Function<span class="token operator">:</span> Emitter<span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token constant">LEAK_WARNING_THRESHHOLD</span><span class="token operator">:</span> <span class="token number">175</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">_noop</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token function">Function</span> <span class="token punctuation">(</span>anonymous<span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token number">666</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>事件监听触发的逻辑均正常，从这儿我们可以理解，传递this的目的是为了让监听回调函数内的this作用域指向正确~</p>
<h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结"><span>总结</span></a></h2>
<p>EventEmitter作为一个非常重要的设计模式实现，常常应用于各类大型系统中作为事件代理用于模块间时间调度和监听，因此一个健壮的事件触发器的设计显得尤为重要。Theia当中的EventEmitter中还有几个精妙的设计值得我们去学习：</p>
<ol>
<li>对每个事件的第一个Listener的建立和最后一个Listener的卸载的时机，提供了一个回调函数，每个Listener里都会在对应的时机可以声明回调函数用于进行特殊处理。</li>
<li>Emitter的dispose做的十分到位，除了每个Listener可以触发对应的removeListener操作，还可以对整个Emitter做dispose操作，保证不会出现泄漏问题。</li>
<li>每当新建立一个Listener，都会对当前事件的Listener数量进行校验，当Listener数量达到设定的最大值时，除了会提示警报以外，还会直接将多余的Listener进行存储，方便监听dispose时进行清理，不会造成泄露问题。</li>
</ol>
</div></template>


